#!/usr/bin/env bash

# Quick Setup Guide - Data Models & Storage

echo "🚀 AI Image Generator - Data Models Setup"
echo "=========================================="
echo ""

echo "📋 QUICK CHECKLIST:"
echo ""
echo "[ ] 1. Cloudflare Setup"
echo "[ ] 2. Update wrangler.toml"
echo "[ ] 3. Test Locally"
echo "[ ] 4. Deploy"
echo ""

echo "=========================================="
echo "STEP 1: CLOUDFLARE SETUP"
echo "=========================================="
echo ""
echo "Create D1 Database:"
echo "  wrangler d1 create image_generator"
echo ""
echo "Create R2 Bucket:"
echo "  wrangler r2 bucket create image_generator"
echo ""

echo "=========================================="
echo "STEP 2: UPDATE wrangler.toml"
echo "=========================================="
echo ""
echo "Update these values in backend/wrangler.toml:"
echo ""
echo "  [env.development]"
echo "  [[d1_databases]]"
echo "  binding = \"DB\""
echo "  database_name = \"image_generator\""
echo "  database_id = \"YOUR_DATABASE_ID_HERE\""
echo ""
echo "  [[r2_buckets]]"
echo "  binding = \"IMAGE_GENERATOR\""
echo "  bucket_name = \"image_generator\""
echo ""

echo "=========================================="
echo "STEP 3: TEST LOCALLY"
echo "=========================================="
echo ""
echo "cd backend"
echo "npm install"
echo "npm run dev"
echo ""
echo "This will:"
echo "  ✓ Start backend on http://localhost:8787"
echo "  ✓ Auto-create database tables"
echo "  ✓ Ready for local testing"
echo ""

echo "=========================================="
echo "DATABASE SCHEMA"
echo "=========================================="
echo ""
echo "Users Table:"
echo "  - id (UUID)"
echo "  - email (Unique)"
echo "  - google_id (Unique)"
echo "  - first_name, last_name"
echo "  - roles (JSON: [ADMIN, USER])"
echo "  - language (en, es, etc.)"
echo "  - coins (Integer)"
echo "  - created_at, updated_at"
echo ""
echo "Images Table:"
echo "  - id (UUID)"
echo "  - user_id (FK → users.id)"
echo "  - type (GENERATED | UPLOADED)"
echo "  - status (PENDING | PROCESSING | COMPLETED | FAILED)"
echo "  - title, description, prompt"
echo "  - storage_key, storage_url"
echo "  - thumbnail_key, thumbnail_url (optional)"
echo "  - metadata (JSON)"
echo "  - coins_used (Integer)"
echo "  - created_at, updated_at"
echo ""

echo "=========================================="
echo "STORAGE STRUCTURE"
echo "=========================================="
echo ""
echo "R2 Bucket: image_generator"
echo "  └── images/"
echo "      └── {userId}/"
echo "          ├── {timestamp}-filename1.png"
echo "          ├── {timestamp}-filename2.jpg"
echo "          └── ..."
echo ""

echo "=========================================="
echo "API PATTERN"
echo "=========================================="
echo ""
echo "1. Find or create user:"
echo "   const user = await UserRepository.findOrCreateByGoogle(env, {...})"
echo ""
echo "2. Check coin balance:"
echo "   if (!user.canAffordFeature(100)) return error('Insufficient coins')"
echo ""
echo "3. Generate/upload image:"
echo "   const uploaded = await StorageService.uploadBuffer(env, buffer, filename, userId, type)"
echo ""
echo "4. Create database record:"
echo "   const image = await ImageRepository.create(env, {...})"
echo ""
echo "5. Deduct coins:"
echo "   await UserRepository.deductCoins(env, userId, 100)"
echo ""
echo "6. Return result:"
echo "   return success({ image: image.toJSON() })"
echo ""

echo "=========================================="
echo "KEY FEATURES"
echo "=========================================="
echo ""
echo "✅ Users:"
echo "   - Create from Google OAuth"
echo "   - Manage roles (ADMIN, USER)"
echo "   - Track coins balance"
echo "   - Deduct/add coins"
echo ""
echo "✅ Images:"
echo "   - Store metadata"
echo "   - Link to users"
echo "   - Track generation cost"
echo "   - Support for thumbnails"
echo ""
echo "✅ Storage:"
echo "   - Upload to R2"
echo "   - Organize by user"
echo "   - Generate public URLs"
echo "   - Delete files"
echo ""

echo "=========================================="
echo "EXAMPLE USAGE"
echo "=========================================="
echo ""
echo "// Generate image with coin deduction"
echo "const user = await UserRepository.findById(env, userId)"
echo ""
echo "if (!user.canAffordFeature(100)) {"
echo "  return error('Need 100 coins')"
echo "}"
echo ""
echo "const uploaded = await StorageService.uploadBuffer("
echo "  env, imageBuffer, 'generated.png', userId, 'image/png'"
echo ")"
echo ""
echo "const image = await ImageRepository.create(env, {"
echo "  userId: user.id,"
echo "  type: ImageType.GENERATED,"
echo "  title: 'My Image',"
echo "  storageKey: uploaded.key,"
echo "  storageUrl: uploaded.url,"
echo "  coinsUsed: 100"
echo "})"
echo ""
echo "await UserRepository.deductCoins(env, user.id, 100)"
echo ""
echo "return success({ image: image.toJSON() })"
echo ""

echo "=========================================="
echo "TROUBLESHOOTING"
echo "=========================================="
echo ""
echo "❌ Database not found?"
echo "   Fix: Check database ID in wrangler.toml"
echo "   Run: wrangler d1 list"
echo ""
echo "❌ R2 bucket not accessible?"
echo "   Fix: Check bucket name in wrangler.toml"
echo "   Run: wrangler r2 bucket list"
echo ""
echo "❌ Tables not created?"
echo "   Fix: Ensure DatabaseInit.initialize() is called"
echo "   Check: Look at console logs for table creation"
echo ""

echo "=========================================="
echo "DOCUMENTATION"
echo "=========================================="
echo ""
echo "📖 Read these files:"
echo ""
echo "  1. backend/DATA_MODELS.md"
echo "     - Complete schema documentation"
echo "     - Model and repository API"
echo "     - Usage examples"
echo ""
echo "  2. backend/CLOUDFLARE_SETUP.md"
echo "     - Step-by-step Cloudflare setup"
echo "     - Create databases and buckets"
echo "     - Configuration tips"
echo ""
echo "  3. backend/IMPLEMENTATION_SUMMARY.md"
echo "     - Overview of what was created"
echo "     - File locations"
echo "     - Architecture benefits"
echo ""

echo "=========================================="
echo "NEXT STEPS"
echo "=========================================="
echo ""
echo "1. Run: cd backend && wrangler d1 create image_generator"
echo "2. Run: wrangler r2 bucket create image_generator"
echo "3. Update: wrangler.toml with database_id and bucket_name"
echo "4. Run: npm run dev"
echo "5. Create: Image generation endpoints"
echo "6. Test: Using your frontend"
echo ""

echo "=========================================="
echo ""
echo "Ready to implement Nanobanana integration! 🎉"
echo ""
